apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace:  argocd
spec:
  destination:
    namespace: frontend
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: config/frontend
    repoURL: https://github.com/FUnigrad/funiverse-infra-config
    targetRevision: dev
  syncPolicy:
    automated:
      prune: true
---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: backend
#   namespace:  argocd
# spec:
#   destination:
#     server: https://kubernetes.default.svc
#   project: default
#   source:
#     directory:
#       jsonnet: {}
#       recurse: true
#     path: config/backend
#     repoURL: https://github.com/FUnigrad/funiverse-infra-config
#     targetRevision: dev
#   syncPolicy:
#     automated:
#       prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system
  namespace:  argocd
spec:
  destination:
    namespace: system
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: config/system
    repoURL: https://github.com/FUnigrad/funiverse-infra-config
    targetRevision: dev
  syncPolicy:
    automated:
      prune: true