apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: argocd-server-ingress
  namespace: argocd
spec:
  host: argocd.admin.funiverse.world
  # tls:
  #   secretName: my-tls-secret
  upstreams:
  - name: argocd
    service: argocd-server
    port: 80
  routes:
  - path: /
    action:
      pass: argocd