apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: system
data:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: mydb
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb
  SPRING_DATASOURCE_USERNAME: root
  SPRING_JPA_HIBERNATE_DDL_AUTO: update