apiVersion: apps/v1
kind: Deployment
metadata:
  name: authen-service
  namespace: system
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      type: service
      name: authen-service
  template:
    metadata:
      labels:
        type: service
        name: authen-service
    spec:
      containers:
      - name: application
        image: funiverse/authen-service@sha256:3a2ba6ad85fb4442bb80cdeb8744cef7244442ff9acecec140b922d76248b216
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: authen-service
  namespace: system
spec:
  type: LoadBalancer
  ports:
  - name: http 
    port: 8000
    targetPort: 8000
    nodePort: 30001
  selector:
    type: service
    name: authen-service
