apiVersion: apps/v1
kind: Deployment
metadata:
  name: authen-service
  namespace: system
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      type: service
      name: authen-service
  template:
    metadata:
      labels:
        type: service
        name: authen-service
    spec:
      containers:
      - name: application
        image: funiverse/authen-service@sha256:7604988ef23625312f25e690cdb4fe092c79118914945590b1612e66ac148ddc
        ports:
        - containerPort: 8000
        env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: MYSQL_ROOT_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO
---
apiVersion: v1
kind: Service
metadata:
  name: authen-service
  namespace: system
spec:
  type: LoadBalancer
  ports:
  - name: http 
    port: 8000
    targetPort: 8000
    nodePort: 30001
  selector:
    type: service
    name: authen-service
