apiVersion: apps/v1
kind: Deployment
metadata:
  name: authen-service
  namespace: system
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      type: service
      name: authen-service
  template:
    metadata:
      labels:
        type: service
        name: authen-service
    spec:
      containers:
      - name: application
        image: funiverse/authen-service@sha256:4826c9eaecdf608fb949117f8e2bfa3899f5c4dca405b2b42b16adc860f319fb
        ports:
        - containerPort: 8000
        env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: MYSQL_ROOT_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO
---
apiVersion: v1
kind: Service
metadata:
  name: authen-service
  namespace: system
spec:
  ports:
  - name: http 
    port: 8000
    targetPort: 8000
  selector:
    type: service
    name: authen-service
---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: authen-svc-vs
  namespace: system
spec:
  host: authen.system.funiverse.world
  upstreams:
  - name: authen-service
    service: authen-service
    port: 8000
  routes:
  - path: /
    action:
      pass: authen-service
