apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: system
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: config
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: config
              key: MYSQL_DATABASE
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: conf
          mountPath: /etc/mysql/conf.d
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-volume
      - name: conf
        configMap:
          name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: system
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30004
  selector:
    app: mysql