---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: go-client
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "configmaps", "persistentvolumeclaims"]
    verbs: ["get", "create", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "create", "delete"]
  - apiGroups: ["k8s.nginx.org"]
    resources: ["VirtualServer"]
    verbs: ["get", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1 
kind: ClusterRoleBinding
metadata:
  name: go-client
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: go-client
subjects:
  - kind: ServiceAccount
    name: default
    namespace: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-service
  namespace: system
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      type: service
      name: workspace-service
  template:
    metadata:
      labels:
        type: service
        name: workspace-service
    spec:
      containers:
      - name: application
        image: funiverse/workspace-service@sha256:c00d71ac9fb7b6260132a00ed7ae75fcaf6ad071f750bc9875d69730eb7dfea8
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: workspace-service
  namespace: system
spec:
  type: NodePort
  ports:
  - name: http 
    port: 8080
    targetPort: 8080
    nodePort: 30002
  selector:
    type: service
    name: workspace-service