apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-service
  namespace: system
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      type: service
      name: workspace-service
  template:
    metadata:
      labels:
        type: service
        name: workspace-service
    spec:
      containers:
      - name: application
        image: funiverse/workspace-service@sha256:1af738257b3e871f79e044b536ca234668dacb8a79ad60a00f6545729ad32638
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: workspace-service
  namespace: system
spec:
  type: LoadBalancer
  ports:
  - name: http 
    port: 8080
    targetPort: 8080
    nodePort: 30002
  selector:
    type: service
    name: workspace-service