---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: go-client
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "configmaps", "persistentvolumeclaims", "services"]
    verbs: ["get", "create", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "create", "delete"]
  - apiGroups: ["k8s.nginx.org"]
    resources: ["virtualservers"]
    verbs: ["get", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1 
kind: ClusterRoleBinding
metadata:
  name: go-client
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: go-client
subjects:
  - kind: ServiceAccount
    name: default
    namespace: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-service
  namespace: system
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      type: service
      name: workspace-service
  template:
    metadata:
      labels:
        type: service
        name: workspace-service
    spec:
      containers:
      - name: application
        image: funiverse/workspace-service:latest
        ports:
        - containerPort: 8080
        # livenessProbe:
        #   httpGet: 
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 3
        #   periodSeconds: 3 
---
apiVersion: v1
kind: Service
metadata:
  name: workspace-service
  namespace: system
spec:
  type: NodePort
  ports:
  - name: http 
    port: 8080
    targetPort: 8080
    nodePort: 30002
  selector:
    type: service
    name: workspace-service
---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: workspace-svc-vs
  namespace: system
spec:
  host: workspace.system.funiverse.world
  # tls:
  #   secret: workspace-system-ssl
  #   cert-manager:
  #     cluster-issuer: letsencrypt-prod
  upstreams:
  - name: workspace-service
    service: workspace-service
    port: 8080
  routes:
  - path: /
    action:
      pass: workspace-service
