apiVersion: apps/v1
kind: Deployment
metadata:
  name: landingpage-web-app
  namespace: frontend
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      type: frontend
      name: landingpage-web-app
  template:
    metadata:
      labels:
        type: frontend
        name: landingpage-web-app
    spec:
      containers:
      - name: application
        image: funiverse/funiverse-landing@sha256:166485fc107eed25745515a76d67c8426d6b62aaf54a03d9a11ebb2ab55c81bb
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: landingpage-web-app
  namespace: frontend
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 3000
    nodePort: 31000
  selector:
    type: frontend
    name: landingpage-web-app
---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: landingpage-web-app-vs
  namespace: frontend
spec:
  host: funiverse.world
  tls:
    secret: funiverse-world-ssl
    cert-manager:
      cluster-issuer: letsencrypt-prod
  upstreams:
  - name: landingpage-web-app
    service: landingpage-web-app
    port: 80
  routes:
  - path: /
    action:
      pass: landingpage-web-app
