apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-admin-web-app
  namespace: frontend
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      type: frontend
      name: system-admin-web-app
  template:
    metadata:
      labels:
        type: frontend
        name: system-admin-web-app
    spec:
      containers:
      - name: application
        image: funiverse/funiverse-web-sa@sha256:cb1699f89190d71e088738e429eb1c9b81e478a8d1bba587bdf08bbe093661cf
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: system-admin-web-app
  namespace: frontend
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 31001
  selector:
    type: frontend
    name: system-admin-web-app
---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: system-admin-web-app-vs
  namespace: frontend
spec:
  host: admin.funiverse.world
  upstreams:
  - name: system-admin-web-app
    service: system-admin-web-app
    port: 80
  routes:
  - path: /
    action:
      pass: system-admin-web-app
