apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-web-app
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      type: frontend
      name: workspace-web-app
  template:
    metadata:
      labels:
        type: frontend
        name: workspace-web-app
    spec:
      containers:
      - name: application
        image: funiverse/funiverse-web-app@sha256:8a0be5c9c070b07865beee4171f85ffefc1a536f493bef7397e82a5c7c883f33
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: workspace-web-app
  namespace: frontend
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 3000
    nodePort: 31002
  selector:
    type: frontend
    name: workspace-web-app

