apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-web-app
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      type: frontend
      name: workspace-web-app
  template:
    metadata:
      labels:
        type: frontend
        name: workspace-web-app
    spec:
      containers:
      - name: application
        image: funiverse/funiverse-web-app@sha256:3aea8125de9c0c54d99d33bc647be5a33dd07d7415ba36c608d0fbab5a9ed74e
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: workspace-web-app
  namespace: frontend
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 3000
    nodePort: 31002
  selector:
    type: frontend
    name: workspace-web-app

