apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-admin-web-app
  namespace: frontend
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      type: frontend
      name: workspace-admin-web-app
  template:
    metadata:
      labels:
        type: frontend
        name: workspace-admin-web-app
    spec:
      containers:
      - name: application
        image: funiverse/funiverse-web-admin@sha256:8ec7fddf677dbbaa70accc8c55af4b3e7067e4e82c6068b0251cb088fcddc3a3
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: workspace-admin-web-app
  namespace: frontend
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 31003
  selector:
    type: frontend
    name: workspace-admin-web-app

