apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-admin-web-app
  namespace: frontend
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      type: frontend
      name: workspace-admin-web-app
  template:
    metadata:
      labels:
        type: frontend
        name: workspace-admin-web-app
    spec:
      containers:
      - name: application
        image: funiverse/funiverse-web-admin@sha256:4412034882044f6f26e57da08ca14b57e2ed8b4510736db9d8362278eb182235
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: workspace-admin-web-app
  namespace: frontend
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 31003
  selector:
    type: frontend
    name: workspace-admin-web-app

