apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-admin-web-app
  namespace: frontend
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      type: frontend
      name: workspace-admin-web-app
  template:
    metadata:
      labels:
        type: frontend
        name: workspace-admin-web-app
    spec:
      containers:
      - name: application
        image: funiverse/funiverse-web-admin@sha256:f3f7e539f5022d2d63ddedef7a7b661bc941440a56da25be3297e31976314ddc
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: workspace-admin-web-app
  namespace: frontend
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 31003
  selector:
    type: frontend
    name: workspace-admin-web-app

