apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      type: service
      name: app-service
  template:
    metadata:
      labels:
        type: service
        name: app-service
    spec:
      containers:
      - name: jdk
        image: maven:3.8.7-eclipse-temurin-17
        ports:
        - containerPort: 80
        command:
        - "/bin/bash"
        - "-c"
        - "sleep 3600"
        volumeMounts:
        - name: volume-2
          mountPath: /workdir
      volumes:
      - name: volume-2
        hostPath:
          path: /home/ubuntu/9-funiverse-authen-service
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: dev
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    type: service
    name: app-service

