apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-admin-web-app
  namespace: frontend
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      type: frontend
      name: workspace-admin-web-app
  template:
    metadata:
      labels:
        type: frontend
        name: workspace-admin-web-app
    spec:
      containers:
      - name: application
        image: funiverse/funiverse-web-admin@sha256:5e77d1127b31491d808194de666e16ee17df4515fb88449717e87e365e5aeab2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: workspace-admin-web-app
  namespace: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    type: frontend
    name: workspace-admin-web-app

