apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: system-admin-web-app-vs
  namespace: frontend
spec:
  host: admin.funiverse.world
  upstreams:
  - name: system-admin-web-app
    service: system-admin-web-app
    port: 80
  routes:
  - path: /
    action:
      pass: system-admin-web-app