apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume
  namespace: dev
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi