apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service
  namespace: dev
spec:
  replicas: 1
  revisionHistoryLimit: 0
  minReadySeconds: 10
  selector:
    matchLabels:
      type: service
      name: app-service
  template:
    metadata:
      labels:
        type: service
        name: app-service
    spec:
      containers:
      - name: application
        image: funiverse/app-service@sha256:b6ce6c9ef080a19d84c85c4b98031c7df74cf4fff86e9ce208d3f1b8f8d3d148
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: config
                key: SPRING_DATASOURCE_URL
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              configMapKeyRef:
                name: config
                key: SPRING_DATASOURCE_USERNAME
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: config
                key: MYSQL_ROOT_PASSWORD
          - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            valueFrom:
              configMapKeyRef:
                name: config
                key: SPRING_JPA_HIBERNATE_DDL_AUTO
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: dev
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
    nodePort: 30000
  selector:
    type: service
    name: app-service

