apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service
  namespace: dev
spec:
  replicas: 2
  revisionHistoryLimit: 0
  minReadySeconds: 10
  selector:
    matchLabels:
      type: service
      name: app-service
  template:
    metadata:
      labels:
        type: service
        name: app-service
    spec:
      containers:
      - name: application
        image: funiverse/app-service@sha256:9cb6f0d47b198468f98c278eaf3dcd8f14a0a3f252113dd4cdef51985ba5303c
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: config
                key: SPRING_DATASOURCE_URL
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              configMapKeyRef:
                name: config
                key: SPRING_DATASOURCE_USERNAME
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: config
                key: MYSQL_ROOT_PASSWORD
          - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            valueFrom:
              configMapKeyRef:
                name: config
                key: SPRING_JPA_HIBERNATE_DDL_AUTO
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: dev
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
    nodePort: 30000
  selector:
    type: service
    name: app-service

