apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: admin-virtualserver
  namespace: frontend
spec:
  host: admin.dev.funiverse.world
  upstreams:
  - name: workspace-admin-web-app
    service: workspace-admin-web-app
    port: 80
  routes:
  - path: /
    route:  frontend/workspace-admin-web-app-route
  - path: ~ /api/?(.*)
    route: dev/app-service-route
---
apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: admin-app-service-route
  namespace: dev
spec:
  host: admin.dev.funiverse.world
  upstreams:
  - name: app-service
    service: app-service
    port: 8080
  subroutes:
  - path: ~ /api/?(.*)
    action:
      proxy:
        upstream: app-service
        rewritePath: /$1
---
apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: workspace-admin-web-app-route
  namespace: frontend
spec:
  host: admin.dev.funiverse.world
  upstreams:
  - name: workspace-admin-web-app
    service: workspace-admin-web-app
    port: 80
  subroutes:
  - path: /
    action:
      pass: workspace-admin-web-app
