apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: admin-virtualserver
  namespace: frontend
spec:
  host: admin.dev.funiverse.world
  upstreams:
  - name: workspace-admin-web-app
    service: workspace-admin-web-app
    port: 80
  routes:
  - path: /
    route:  frontend/workspace-admin-web-app-route
  - path: ~ /api/?(.*)
    route: dev/app-service-route