apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: workspace-virtualserver
  namespace: dev
spec:
  host: dev.funiverse.world
  routes:
  - path: /
    route: frontend/workspace-web-app-route
  - path: ~ /api/?(.*)
    route: dev/app-service-route
--- 
apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: app-service-route
  namespace: dev
spec:
  host: dev.funiverse.world
  upstreams:
  - name: app-service
    service: app-service
    port: 8080
  subroutes:
  - path: ~ /api/?(.*)
    action:
      proxy:
        upstream: app-service
        rewritePath: /$1
---
apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: workspace-web-app-route
  namespace: frontend
spec:
  host: dev.funiverse.world
  upstreams:
  - name: workspace-web-app
    service: workspace-web-app
    port: 80
  subroutes:
  - path: /
    action:
      pass: workspace-web-app