apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-service
  namespace: system
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      type: service
      name: workspace-service
  template:
    metadata:
      labels:
        type: service
        name: workspace-service
    spec:
      containers:
      - name: application
        image: funiverse/workspace-service@sha256:6ac3d80f311dd5368c9ed6c1d5bb80503fc6e82c6f075dee182f1cbc47f5d349
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: workspace-service
  namespace: system
spec:
  type: LoadBalancer
  ports:
  - name: http 
    port: 8080
    targetPort: 8080
    nodePort: 30002
  selector:
    type: service
    name: workspace-service